<!-- routes.regex.type="regex"
routes.regex.match="#^/regex/([0-9]+)/([^/]*)#"
;routes.regex.route.module=index
routes.regex.route.controller=regex
routes.regex.route.action=index
routes.regex.map.1=id
routes.regex.map.2=name

;路由
routes.posts.type="posts"
routes.posts.match="#^/posts/([0-9]+)/([^/]*)#"
;routes.posts.route.module=index
routes.posts.route.controller=posts
routes.posts.route.action=detail
routes.posts.map.1=id
routes.posts.map.2=name -->